import 'tailwindcss/tailwind.css'
import '../styles/globals.css'
import type { AppProps } from 'next/app'
import Nav from '../components/Nav/Nav'
import Footer from '../components/Footer/Footer'
import Head from 'next/head'

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>Test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="w-full py-4 text-center font-bold bg-red-600 text-white">
        <p className="text-xl">Under Development.</p>
        <p>Contact us at support@feastingtogether.com for more information.</p>
      </div>
      <Component {...pageProps} />
    </>
  ) 
}
export default MyApp
